// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aevbzewqdwjcfazddwsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldmJ6ZXdxZHdqY2ZhemRkd3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTYxMDcsImV4cCI6MjA3MzA3MjEwN30.Ia6aSHoZwLMvX2KBO7F_Ks45Q6FuLqiAartzmHfepbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});